# Railway Configuration
# Este arquivo indica que o Railway deve fazer deploy da pasta server/

[build]
command = "cd server && npm install"

[deploy]
startCommand = "cd server && node index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
